name: Create new draft release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Create module.zip
        run: |
          pnpm install
          pnpm run build
          pnpm prune --prod
          zip -r module.zip *
      - name: Create new draft release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.ref_name }}
          draft: true
          title: ${{ github.ref_name }}
          files: |
            module.zip
            module.json