name: Create new draft release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create module.zip
        run: |
          sudo apt install nodejs npm -y
          npm install -D
          npm run build
          zip -r module.zip ${{ github.workspace }}
      - name: Create new draft release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.ref_name }}
          draft: true
          title: ${{ github.ref_name }}
          files: |
            module.zip
            module.json